import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import dayjs from "dayjs";
import { getArticleList } from "./api/article/[id]";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  const result = await getArticleList();
  return {
    props: {
      articleList: result,
    },
  };
}

export default function Home({ articleList }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <div className="flex flex-col w-10/12 mt-10">
          {articleList.list.map((item: any) => {
            return (
              <Link href={`/article/${item.id}`} className="mh-20 bg-white rounded-lg mb-3 p-8 flex-col flex" key={item.id}>
                <span className="text-lg font-medium">{item.title}</span>
                <span>{dayjs(item.updateTime).format("YYYY-MM-DD HH:MM")}</span>
              </Link>
            );
          })}
        </div>
        <Link href="/about" className="fixed bottom-8 text-xl">
          关于我
        </Link>
      </main>
    </>
  );
}
