import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import dayjs from "dayjs";
import { getArticleList } from "./api/article/[id]";

const inter = Inter({ subsets: ["latin"] });

export async function getServerSideProps() {
  const result = await getArticleList();
  return {
    props: {
      articleList: result,
    },
  };
}

export default function Home({ articleList }: any) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <Link href="/about" className="blue1 text-3xl font-bold underline">关于我</Link>
        <p className="fixed bottom-20 left-0 flex h-24 w-full items-end justify-center bg-gradient-to-t from-white via-white dark:from-black dark:via-black lg:static lg:h-auto lg:w-auto lg:bg-none" >
          test
        </p>
        {articleList.list.map((item: any) => {
          return (
            <div key={item.id}>
              <span>{item.title}</span>
              <span>{dayjs(item.updateTime).format("YYYY-MM-DD HH:MM")}</span>
              <Link href={`/article/${item.id}`}>去查看</Link>
            </div>
          );
        })}
      </main>
    </>
  );
}
