name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18" # 指定node版本

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to server
        uses: easingthemes/ssh-deploy@v2
        env:
          # 私钥 这里是阿里云的私钥 使用本地的私钥
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          # scp参数
          ARGS: "-avzr --delete"
          # 源目录
          SOURCE: ".next"
          # 服务器ip：换成你的服务器IP
          REMOTE_HOST: ${{ secrets.SERVER_IP }}
          # 用户
          REMOTE_USER: ${{ secrets.SERVER_USERNAME }}
          # 目标地址
          TARGET: "/www/site/next-blog"
