name: Deploy to Docker Container

on:
  push:
    branches:
      - main  # 触发分支

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read package.json version
        id: package
        run: echo "::set-output name=version::$(node -e 'console.log(require("./package.json").version)')"

      - name: Build and push Docker image
        run: |
          export PKM_VERSION_DEFAULT=$(node -pe "require('./package.json').version")
          export SEMANTIC_VERSION=`npm run semantic-release --dry-run --registry=https://registry.npmmirror.com | grep -oP 'Published release \K.*? ' | sed s/[[:space:]]//g`
          docker build -t nextjs-blog .
          IMAGE_TAG=$SEMANTIC_VERSION
          docker tag nextjs-blog:latest abnery/nextjs-blog:$IMAGE_TAG
          docker tag nextjs-blog:latest abnery/nextjs-blog:latest
          docker push abnery/nextjs-blog:$IMAGE_TAG
          docker push abnery/nextjs-blog:latest
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker pull abnery/nextjs-blog:$IMAGE_TAG
            docker stop nextjs-blog || true
            docker rm nextjs-blog || true
            docker run -d --name nextjs-blog -p 3000:3000 abnery/nextjs-blog:$IMAGE_TAG
